"""empty message

Revision ID: 8debf17ba136
Revises: 0f03c28e72e5
Create Date: 2021-03-23 21:38:47.873202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8debf17ba136'
down_revision = '0f03c28e72e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
